### ISSUE TITLE
obtainUnicode fails in the browser

### ISSUE THREAD

**Issue by ysangkok** [Jxck/utf8-encoding#1]
`Uncaught TypeError: undefined is not a function`

Apparently, it is only `require`d if not in the browser. This breaks the script.

**Comment by Jxck** [comment]
did you build a typescript to js ?
or see https://github.com/Jxck/utf8-encoding/tree/release includes build js.

**Comment by ysangkok** [comment]
no, sorry for the inconvenience, i thought it would work straight outta npm.

**Comment by Jxck** [comment]
npm install includs js which result of ts.
thanks.

**Comment by ysangkok** [comment]
obtainUnicode is a local and is only conditionally assigned (https://github.com/Jxck/utf8-encoding/blob/master/utf8-encoding.ts#L26). I got the same problem again now, and I can't seem to understand how the current code is correct.

**Comment by Jxck** [comment]
this code don't require dependencies (https://github.com/jxck/obtain-unicode) in window.
you need to load obtain-unicode in script tag by yourself in browser.

**Comment by ysangkok** [comment]
@Jxck even if I load obtain-unicode manually in the browser, the generated code from utf8-encoding will shadow the global `window.obtainUnicode`, because the module system will enclose it in a giant function block. I verified in the debugger myself that obtain-unicode is loaded correctly, but after the generated `var obtainUnicode; if (window) obtainUnicode = ...;` stuff, it is undefined, which is the problem.

I can construct a test case if you need it.

**Comment by Jxck** [comment]
> I can construct a test case if you need it.

could you give me that ?

**Comment by ysangkok** [comment]
1. first, create a new directory and enter it
2. execute `npm install utf8-encoding`
3. make a new file, `test.js`, with the contents:

```
var encoder = new TextEncoder();
var decoder = new TextDecoder();
console.log(encoder.encode("beer!🍻"));
// Uint8Array[98, 101, 101, 114, 33, 240, 159, 141, 187]
console.log(decoder.decode(new Uint8Array([98, 101, 101, 114, 33, 240, 159, 141, 187])));
// "beer!🍻
```
1. execute `browserify test.js > out.js`
2. make a new file, `out.html`, with the contents: `<script src=out.js></script>`
3. open `out.html` in the browser and check the console
4. the error console reports `Uncaught TypeError: obtainUnicode is not a function`
